/* 
 * Player API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Foobar2000.RESTClient.Client;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;

namespace Foobar2000.RESTClient.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IArtworkApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get artwork for specific playlist item
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Foobar2000.RESTClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playlistId">Playlist id or index</param>
        /// <param name="index">Item index</param>
        /// <returns></returns>
        void GetArtwork (string playlistId, string index);

        /// <summary>
        /// Get artwork for specific playlist item
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Foobar2000.RESTClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playlistId">Playlist id or index</param>
        /// <param name="index">Item index</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> GetArtworkWithHttpInfo (string playlistId, string index);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get artwork for specific playlist item
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Foobar2000.RESTClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playlistId">Playlist id or index</param>
        /// <param name="index">Item index</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task GetArtworkAsync (string playlistId, string index);

        /// <summary>
        /// Get artwork for specific playlist item
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Foobar2000.RESTClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playlistId">Playlist id or index</param>
        /// <param name="index">Item index</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> GetArtworkAsyncWithHttpInfo (string playlistId, string index);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ArtworkApi : IArtworkApi
    {
        private Foobar2000.RESTClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ArtworkApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ArtworkApi(String basePath)
        {
            this.Configuration = new Foobar2000.RESTClient.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Foobar2000.RESTClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ArtworkApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ArtworkApi(Foobar2000.RESTClient.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Foobar2000.RESTClient.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Foobar2000.RESTClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Foobar2000.RESTClient.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Foobar2000.RESTClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get artwork for specific playlist item 
        /// </summary>
        /// <exception cref="Foobar2000.RESTClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playlistId">Playlist id or index</param>
        /// <param name="index">Item index</param>
        /// <returns></returns>
        public void GetArtwork (string playlistId, string index)
        {
             GetArtworkWithHttpInfo(playlistId, index);
        }

        /// <summary>
        /// Get artwork for specific playlist item 
        /// </summary>
        /// <exception cref="Foobar2000.RESTClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playlistId">Playlist id or index</param>
        /// <param name="index">Item index</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> GetArtworkWithHttpInfo (string playlistId, string index)
        {
            // verify the required parameter 'playlistId' is set
            if (playlistId == null)
                throw new ApiException(400, "Missing required parameter 'playlistId' when calling ArtworkApi->GetArtwork");
            // verify the required parameter 'index' is set
            if (index == null)
                throw new ApiException(400, "Missing required parameter 'index' when calling ArtworkApi->GetArtwork");

            var localVarPath = "/artwork/{playlistId}/{index}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (playlistId != null) localVarPathParams.Add("playlistId", this.Configuration.ApiClient.ParameterToString(playlistId)); // path parameter
            if (index != null) localVarPathParams.Add("index", this.Configuration.ApiClient.ParameterToString(index)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetArtwork", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Get artwork for specific playlist item 
        /// </summary>
        /// <exception cref="Foobar2000.RESTClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playlistId">Playlist id or index</param>
        /// <param name="index">Item index</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task GetArtworkAsync (string playlistId, string index)
        {
             await GetArtworkAsyncWithHttpInfo(playlistId, index);

        }

        /// <summary>
        /// Get artwork for specific playlist item 
        /// </summary>
        /// <exception cref="Foobar2000.RESTClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="playlistId">Playlist id or index</param>
        /// <param name="index">Item index</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> GetArtworkAsyncWithHttpInfo (string playlistId, string index)
        {
            // verify the required parameter 'playlistId' is set
            if (playlistId == null)
                throw new ApiException(400, "Missing required parameter 'playlistId' when calling ArtworkApi->GetArtwork");
            // verify the required parameter 'index' is set
            if (index == null)
                throw new ApiException(400, "Missing required parameter 'index' when calling ArtworkApi->GetArtwork");

            var localVarPath = "/artwork/{playlistId}/{index}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (playlistId != null) localVarPathParams.Add("playlistId", this.Configuration.ApiClient.ParameterToString(playlistId)); // path parameter
            if (index != null) localVarPathParams.Add("index", this.Configuration.ApiClient.ParameterToString(index)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetArtwork", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

    }
}
