/* 
 * Player API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Runtime.Serialization;

namespace Foobar2000.RESTClient.Model
{
    /// <summary>
    /// Defines VolumeType
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum VolumeType
    {
        
        /// <summary>
        /// Enum Db for value: db
        /// </summary>
        [EnumMember(Value = "db")]
        Db = 1,
        
        /// <summary>
        /// Enum Linear for value: linear
        /// </summary>
        [EnumMember(Value = "linear")]
        Linear = 2
    }

}
